### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Leanplum/Leanplum-GTM-Tag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The test "Runs applyQueue once script loads" failed. "Test assertion failed:
callInWindow expected to have been called with arguments ("Leanplum.applyQueue", [[object Object],[object Object],[object Object]]), but it was not." is seen. Please resolve the issue.
![Screenshot 2020-06-25 at 2 01 00 PM](https://user-images.githubusercontent.com/53495700/85795042-77ffa080-b6ec-11ea-98ee-4798f1fed469.png)

**Comment by gyoshev** [comment]
Hello @praveena-pappu,

Thank you for the quick template review! I've published a new version of the template that has this resolved.

**Comment by gyoshev** [comment]
@praveena-pappu Do we need to perform additional actions in order to get the tag in the gallery?
